---
#
# Ansible managed
#
repository:
  description: Set up dnsmasq in Debian-like systems.
  homepage: https://buluma.github.io/
  topics: system, networking, dns, ansible, molecule, tox, playbook, hacktoberfest
