---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes
  pre_tasks:
    - name: include vars
      include_vars: "{{ playbook_dir }}/../../tests/vars/main.yml"

  roles:
    - role: buluma.dnsmasq
