---
#
# Ansible managed
#

name: Ansible Molecule

on:
  # Schedule updates (once daily)
  schedule:
    - cron: '1 1 * * *'
  workflow_dispatch:
  push: {branches: ["master", "main", "testing"]}

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: buluma/molecule-action@v5.0.1
        with:
          command: lint
  test:
    needs:
      - lint
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - image: "docker-ubuntu-systemd"
            tag: "bionic"
          - image: "ubuntu"
            tag: "xenial"
          - image: "ubuntu"
            tag: "xenial-20210804"
          - image: "debian"
            tag: "jessie"
          - image: "debian"
            tag: "stretch"
          - image: "debian"
            tag: "buster"
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: disable apparmor for mysql
        run: sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
      - name: parse apparmor for mysql
        run: sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
      - name: molecule
        uses: buluma/molecule-action@v5.0.1
        with:
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}
